import type { Metadata } from "next";
import localFont from "next/font/local";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";
import NavBar from "./NavBar";

// const inter = Inter({ subsets: ["latin"] });

// //change fonts
// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "500"],
//   variable: "--font-roboto",
// });
//custom fonts
const redHatText = localFont({
  src: "../public/fonts/RedHatText-Bold.ttf",
  variable: "--font-redHatText",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "./images/icon.webp",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body className={redHatText.variable} suppressHydrationWarning={true}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
